In [1]:
#1gettting the access to the file 
## download file from internet and saving/ storing in local folder eith file name 

!curl https://raw.githubusercontent.com/MicrosoftLearning/intropython/master/poem1.txt -o poem1.txt
    
#downloaded 
#crated a new file named it 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    56  100    56    0     0     56      0  0:00:01 --:--:--  0:00:01   903


In [2]:
##2 open the file in read mode 
poem_file = open('poem1.txt', 'r') 

## 3 read the data 

poem_contents = poem_file.read()
poem_contents

'Loops I repeat\nloops\nloops\nloops\nI repeat\nuntil I\nbreak\n'

In [3]:
poem_file = open('poem1.txt', 'r') ##.open() to reset read() to the beginning of the file.
p10 = poem_file.read(15).upper()
print(p10, 'This is with upper string\n')

#read with slicing
# poem_file = open('poem1.txt', 'r') #if did not open again it will continue from last read
p10 = poem_file.read()
print(p10[7:26], 'This is with slicing')

LOOPS I REPEAT
 This is with upper string

oops
loops
I repeat This is with slicing


In [4]:
# [ ] review and run example
poem_file = open('poem1.txt', 'r')
poem_part = poem_file.read(15).upper()
print(poem_part, 'This is with upper string\n')
# [ ] review and run example
poem_part = poem_file.read(6).title()
print(poem_part, 'This is with title string\n')
# [ ] review and run example
poem_part = poem_file.read(6)
print(poem_part)
print(poem_part.isalpha(), "isalpha() because of `\\n`")
poem_part
# [ ] review and run example
poem_file = open('poem1.txt', 'r')
poem_text = poem_file.read()
print('\n', poem_text[8:26] , 'This is with slicing\n')

LOOPS I REPEAT
 This is with upper string

Loops
 This is with title string

loops

False isalpha() because of `\n`

 repeat
loops
loops This is with slicing



# My own assignment

In [5]:
# My own exercise from OmniLearn
!curl https://raw.githubusercontent.com/MicrosoftLearning/intropython/master/cities -o cities.txt
    
# Task 1 Save file as text
task_file = open('cities.txt', 'r') 
task_contents = task_file.read()
task_contents

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    56  100    56    0     0     56      0  0:00:01 --:--:--  0:00:01   170


'Beijing\nCairo\nLondon\nNairobi\nNew York City\nSydney\nTokyo\n'

In [16]:
# Task 2 iterate through the characters in cities
print ('-----Task 2-----')
my_file = open('cities.txt', 'r')
my_part = my_file.read(7).upper()
print(my_part, '\nThis is with upper string')

# Task 3 test if .isupper(), if True append the character to a string variable: initials
print ('\n-----Task 3-----')
initials = ''
my_file = open('cities.txt', 'r')
cities = my_file.read()
for city in cities:
    if city.isupper():
        initials += city
print(initials)

# Task 4 else if (elif) character is "\n", if True append the "\n" to initials
print ('\n-----Task 4-----')
initials = ''
my_file = open('cities.txt', 'r')
cities = my_file.read()
for city in cities:
    if city.isupper():
        initials += city
    elif city == '\n':
        initials += city
        
print (initials)

-----Task 2-----
BEIJING 
This is with upper string

-----Task 3-----
BCLNNYCST

-----Task 4-----
B
C
L
N
NYC
S
T



# eLearning (readline & close)

In [32]:
!curl https://raw.githubusercontent.com/MicrosoftLearning/intropython/master/poem1.txt -o poem1.txt

poem_file = open('poem1.txt', 'r') 

## 3 read the data 

# readlines and print as  aslist 
poem_contents = poem_file.readlines()
poem_contents


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    56  100    56    0     0     56      0  0:00:01 --:--:--  0:00:01  1191


['Loops I repeat\n',
 'loops\n',
 'loops\n',
 'loops\n',
 'I repeat\n',
 'until I\n',
 'break\n']

In [33]:
# not good if we dun want to have too much spacing.
for line in poem_contents:
    print(line)

Loops I repeat

loops

loops

loops

I repeat

until I

break



In [34]:
count = 0
for line in poem_contents:
    poem_contents[count] = line[:-1]
    count += 1

print(poem_contents)

['Loops I repeat', 'loops', 'loops', 'loops', 'I repeat', 'until I', 'break']


In [36]:
# [ ] print each list item 
for line in poem_contents:
    print(line)
    
    
#close ot also 

Loops I repeat
loops
loops
loops
I repeat
until I
break


In [37]:
!curl https://raw.githubusercontent.com/MicrosoftLearning/intropython/master/poem1.txt -o poem1.txt

poem_file = open('poem1.txt', 'r') #read mode 

## 3 read the data 

poem_line = poem_file.readline().strip('\n')
while poem_line:
    print(poem_line.capitalize())
    poem_line= poem_file.readline().strip('\n')
     
## 4 close the 
poem_file.close()


Loops i repeat
Loops
Loops
Loops
I repeat
Until i
Break


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    56  100    56    0     0     56      0  0:00:01 --:--:--  0:00:01  1750


In [ ]:
poem_file = open('poem1.txt', 'w') ## write mode 
poem_file.write("im overwrting theloops file")



In [ ]:
poem_file = open('poem1.txt', 'r')

print(poem_file.read())


In [ ]:
poem_file = open('poem1.txt', 'w+')
poem_file.write("first line \n secodn lines \n")

poem_file.seek(0)#go back to the first line 
new_txt = poem_file.read()
print(new_txt)

# eLearning (Numpy)

In [72]:
import numpy as np
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [83]:
np_height = np.array(height)
np_weight = np.array(weight)
print (np_height)
print (np_weight)

bmi = np_weight / np_height ** 2
print ("\nShow caclulated BMI")
print (bmi)

print ("\nShow what BMI is more than 23")
print (bmi > 23)

print ("\nShow the number of BMI that is more than 23")
print (bmi[bmi>23])

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]

Show caclulated BMI
[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]

Show what BMI is more than 23
[False False False  True False]

Show the number of BMI that is more than 23
[24.7473475]


In [106]:
# 2D numpy Arrays
import numpy as np
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],[65.4, 59.2, 63.6, 88.4, 68.7]])
print ("Rows>>> and collum^^^... example i call for number 1.71 \n")
print (np_2d)
print ('\n', np_2d[0,2])
print ('\n', np_2d[:,1:3])
print ('\n', np_2d[1,:])

print ('\n\n',np_2d.shape)

Rows>>> and collum^^^... example i call for number 1.71 

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]

 1.71

 [[ 1.68  1.71]
 [59.2  63.6 ]]

 [65.4 59.2 63.6 88.4 68.7]


 (2, 5)


In [54]:
import numpy as np

# library with many functions 
## for eg:
##if all these pop() split() append() upper() lower() remove() title() insert()
#are stored in library ABCDEFG, 

# to accedd the function , we have to go via the library ABCDEFG

#import ABCDEFG as ab
#ab.pop() 
#ab.split()

In [41]:
# Without numpy cannot add a list
a = [1,1,1]
b = [2,2,2]
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [42]:
import numpy as np
a1 = np.array(a)
b1 = np.array(b)
a1-b1

array([-1, -1, -1])

## numpy functions
1. arrange
2. linspace
3. zeros
4. ones 
5. array

In [43]:
# range of 1-100 display
##(1,100,1) =. startingpoint, ending point, incremental value 
a = []
for i in range(1,100,1):
    a.append(i)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [44]:
# using numpy 
a = np.arange(1,100,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [50]:
# dummy data starting from 1,10 genrate 200 number s
b = np.linspace(1,10,200)
b

array([ 1.        ,  1.04522613,  1.09045226,  1.13567839,  1.18090452,
        1.22613065,  1.27135678,  1.31658291,  1.36180905,  1.40703518,
        1.45226131,  1.49748744,  1.54271357,  1.5879397 ,  1.63316583,
        1.67839196,  1.72361809,  1.76884422,  1.81407035,  1.85929648,
        1.90452261,  1.94974874,  1.99497487,  2.04020101,  2.08542714,
        2.13065327,  2.1758794 ,  2.22110553,  2.26633166,  2.31155779,
        2.35678392,  2.40201005,  2.44723618,  2.49246231,  2.53768844,
        2.58291457,  2.6281407 ,  2.67336683,  2.71859296,  2.7638191 ,
        2.80904523,  2.85427136,  2.89949749,  2.94472362,  2.98994975,
        3.03517588,  3.08040201,  3.12562814,  3.17085427,  3.2160804 ,
        3.26130653,  3.30653266,  3.35175879,  3.39698492,  3.44221106,
        3.48743719,  3.53266332,  3.57788945,  3.62311558,  3.66834171,
        3.71356784,  3.75879397,  3.8040201 ,  3.84924623,  3.89447236,
        3.93969849,  3.98492462,  4.03015075,  4.07537688,  4.12

In [53]:
a1 = np.zeros((2,3,))
a1

array([[0., 0., 0.],
       [0., 0., 0.]])

# assignment 
1. imports and opens a file in append+ mode a+ mode 

2. appends additional data to a file using function write ,
            
            Rio de Janeiro,Brazil,30.0,18.0\n
    
    after writing the cursor is in the endof line 
3.  use the seek(0) to go back to start of line ,goes back to the heading
4. reads from the file using function readline(), reading only the heading 
5. split the header using ','
6. read from the file using function readline(), to read the data_values 

7. while data_values :
    
        7.1 split the data_values using ',' 
        7.2 to displays each city name and month average high   temperature in Celsius
    
    to display the below text 
     City of Rio De Janeiro month ave: highest high is 30.0 Celsius
     
     
     City             = comes from the header_list[0].title() or capitalize() 
     of                =  hardcoded 
     Rio De Janeiro    =  comes from data_values_list[0]
     month ave: highest high = comes from header_list[2]
     is                    =  hardcoded
     30.0                  = data_values_list[2]
     Celsius               =  hardcoded
     
     data_values  = weather.readline(0
     
8. close()





In [ ]:
!curl https://raw.githubusercontent.com/MicrosoftLearning/intropython/master/world_temp_mean.csv -o mean_temp.txt

In [ ]:
#1 open the file 
weather_file = open('mean_temp.txt', "a+")

#2. write the data 
weather_file.write("Rio de Janeiro,Brazil,30.0,18.0\n")

#3. seek(0)
weather_file.seek(0)


#4. read header data and store in a variable heading 
heading = weather_file.readline()
#print(heading)

#5. split of header data to store all the individual header data into a variable heading_+list 

heading_list = heading.split(",")

#6. read the data values and store in a variable data_values 
data_values  = weather_file.readline()


#7. while loop 
while data_values:
    
    # 7.1 split of data values to store all the individual data values into a variable data values list 
    data_values_list  = data_values.split(",")
    
    print( heading_list[0].capitalize(),"of", data_values_list[0], heading_list[2], 
         "is", data_values_list[2], "Celsius")
    
    #7. 2 read the data values and store in a variable data_values 
    data_values = weather_file.readline()
    
#8 close the file 
weather_file.close()    
    

