In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('Student-Pass-Fail-Data.csv')
df.head()

Self_Study_Daily  Tution_Monthly  Pass_Or_Fail
0                 7              27             1
1                 2              43             0
2                 7              26             1
3                 8              29             1
4                 3              42             0

In [7]:
x = df[['Self_Study_Daily', 'Tution_Monthly']]
y = df.Pass_Or_Fail
x.head()

Self_Study_Daily  Tution_Monthly
0                 7              27
1                 2              43
2                 7              26
3                 8              29
4                 3              42

In [8]:
## or 
x = df.drop('Pass_Or_Fail', axis = 1 )
y = df.Pass_Or_Fail
x.head()

Self_Study_Daily  Tution_Monthly
0                 7              27
1                 2              43
2                 7              26
3                 8              29
4                 3              42

In [9]:
y.head()

0    1
1    0
2    1
3    1
4    0
Name: Pass_Or_Fail, dtype: int64

In [ ]:
##split
##model
##fit
## predict

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [35]:
##split
xtrain, xtest ,ytrain, ytest = train_test_split(x, y, random_state = 4  )

In [36]:
##model 
log_reg = LogisticRegression()

In [38]:
##fit
train_model = log_reg.fit(xtrain,ytrain)

In [39]:
#predict 
pred_y = log_reg.predict(xtest)

In [41]:
from sklearn import metrics

In [42]:
## compare bnetween actual y and predicted y 
## acutal y is from ytest , predicted y is from the model predict ()
accuracy = metrics.accuracy_score(ytest ,pred_y )
accuracy_per = 100 * accuracy 
print(accuracy_per)

96.8


In [43]:
## predcit whether my student fail or pass 
student1 = log_reg.predict(np.array([[3,23]]))
student1

array([0])

In [44]:
## predcit whether my student fail or pass 
student2 = log_reg.predict((np.array([5,43]).reshape(1,-1)))
student2

array([0])

In [45]:
## predcit whether my student fail or pass 
student3 = log_reg.predict((np.array([6,53]).reshape(1,-1)))
#log_reg.predict(np.array([[6,53]]))

student3

array([0])

In [47]:
## predcit whether my student fail or pass 
student4 = log_reg.predict((np.array([2,83]).reshape(1,-1)))
student4

array([0])

In [51]:
## predcit whether my student fail or pass 
student5 = log_reg.predict((np.array([3,13]).reshape(1,-1)))
student5

array([1])

In [53]:
## predcit whether my student fail or pass 
student6 = log_reg.predict((np.array([5,13]).reshape(1,-1)))
student6

array([1])

In [55]:
## predcit whether my student fail or pass 
student7 = log_reg.predict((np.array([8,15]).reshape(1,-1)))
student7

array([1])

In [56]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest ,pred_y )
print(cm)

## out of 250 rows of test data 
### 120 + 122 = true = correct predictions 
### 8+0 = false  = wrong predictions 

[[120   8]
 [  0 122]]


In [57]:
df.shape

(1000, 3)

In [61]:
#xtrain, xtest( 75 : 25 split)

(     Self_Study_Daily  Tution_Monthly
 209                 7              26
 452                 1              41
 518                 8              28
 966                 5              34
 925                 7              27
 ..                ...             ...
 897                 6              23
 709                 7              25
 439                 2              33
 174                 7              25
 122                 4              34
 
 [750 rows x 2 columns],
      Self_Study_Daily  Tution_Monthly
 698                 8              28
 577                 7              26
 763                 8              29
 790                 4              38
 520                 7              25
 ..                ...             ...
 642                 9              30
 883                 7              26
 420                 8              29
 446                 5              37
 34                  7              24
 
 [250 rows x 2 columns])

In [62]:
from sklearn.metrics import classification_report
print(classification_report(ytest ,pred_y))

              precision    recall  f1-score   support

           0       1.00      0.94      0.97       128
           1       0.94      1.00      0.97       122

    accuracy                           0.97       250
   macro avg       0.97      0.97      0.97       250
weighted avg       0.97      0.97      0.97       250



In [64]:
##### testing 
import sklearn as sk 
from sklearn import datasets 


In [68]:
iris  = datasets.load_iris()

In [70]:
iris 
## 5 fields 
## 4 fields are input = sepal length, sepal width, petal length, petal width = data
## 1 field = ouput  = target_names = target

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [71]:
x = iris.data
y = iris.target 


In [77]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
##split
##model
##fit
## predict/score 

In [75]:
##split
xtrain, xtest ,ytrain, ytest = train_test_split(x, y, test_size = 0.2  )

In [80]:
from sklearn import neighbors
##model 
cls_kn = neighbors.KNeighborsClassifier()

In [81]:
##fit
train_model_kn = cls_kn.fit(xtrain,ytrain)

In [82]:
cls_kn.score(xtest, ytest)

0.9666666666666667

In [83]:
## other algorithms 
#naive
##split= no need to split again 
##model
from sklearn import naive_bayes 
##model 
cls_nb = naive_bayes.GaussianNB()
##fit
##fit
train_model_nb = cls_nb.fit(xtrain,ytrain)
## predict/score 
cls_nb.score(xtest, ytest)

0.9333333333333333

In [85]:
## other algorithms 
#naive
##split= no need to split again 
##model
from sklearn import  tree 
##model 
cls_dt = tree.DecisionTreeClassifier()
##fit
##fit
train_model_dt = cls_dt.fit(xtrain,ytrain)
## predict/score 
cls_dt.score(xtest, ytest)

0.9333333333333333

In [ ]:
#what to select



